# Generated by Django 5.0.6 on 2024-06-24 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_team_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='user',
        ),
    ]
